#!/bin/sh

set -x

# we're going to loop until we see this var
var="$1"
testVar(){
	systemctl --user show-environment | grep -e "$var=." || return 1
}
while ! testVar
do
	sleep 1
done

# load the environment now that it for sure has the variable
freshenv="$(systemctl --user show-environment)"
eval export $freshenv

# remove the "var" we just looked for
shift

# run the specified command!
# exec will terminate this shell but run the command in the foreground
# it is one of the coolest features of shells!

# caveats:
# 1. there is a maximum limit to the number of arguments passed in- 17
# this is an implementation tradeoff to allow string quoting to work.
# there's probably better ways of doing this! lmk!

# ideally something like exec $* would be workable,
# but that specific command means `await-env MY_VAR sh -c "echo done"` would not work

n="$#"
if [ "$#" -gt 9 ]
then
	arg1="$1"
	[ -n "$1" ] && shift
	arg2="$1"
	[ -n "$1" ] && shift
	arg3="$1"
	[ -n "$1" ] && shift
	arg4="$1"
	[ -n "$1" ] && shift
	arg5="$1"
	[ -n "$1" ] && shift
	arg6="$1"
	[ -n "$1" ] && shift
	arg7="$1"
	[ -n "$1" ] && shift
	arg8="$1"
	[ -n "$1" ] && shift
	arg9="$1"
fi

run=exec
#run="systemd-run --user"

[ "$n" -eq 18 ] && $run "$arg1" "$arg2" "$arg3" "$arg4" "$arg5" "$arg6" "$arg7" "$arg8" "$arg9" "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9"
[ "$n" -eq 17 ] && $run "$arg1" "$arg2" "$arg3" "$arg4" "$arg5" "$arg6" "$arg7" "$arg8" "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9"
[ "$n" -eq 16 ] && $run "$arg1" "$arg2" "$arg3" "$arg4" "$arg5" "$arg6" "$arg7" "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9"
[ "$n" -eq 15 ] && $run "$arg1" "$arg2" "$arg3" "$arg4" "$arg5" "$arg6" "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9"
[ "$n" -eq 14 ] && $run "$arg1" "$arg2" "$arg3" "$arg4" "$arg5" "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9"
[ "$n" -eq 13 ] && $run "$arg1" "$arg2" "$arg3" "$arg4" "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9"
[ "$n" -eq 12 ] && $run "$arg1" "$arg2" "$arg3" "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9"
[ "$n" -eq 11 ] && $run "$arg1" "$arg2" "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9"
[ "$n" -eq 10 ] && $run "$arg1" "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9"

[ "$n" -eq 9 ] && $run "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9"
[ "$n" -eq 8 ] && $run "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8"
[ "$n" -eq 7 ] && $run "$1" "$2" "$3" "$4" "$5" "$6" "$7"
[ "$n" -eq 6 ] && $run "$1" "$2" "$3" "$4" "$5" "$6"
[ "$n" -eq 5 ] && $run "$1" "$2" "$3" "$4" "$5"
[ "$n" -eq 4 ] && $run "$1" "$2" "$3" "$4"
[ "$n" -eq 3 ] && $run "$1" "$2" "$3"
[ "$n" -eq 2 ] && $run "$1" "$2"
[ "$n" -eq 1 ] && $run "$1"
