#!/bin/sh

# filter a env format stdin, picking a variable

# var ot pick
var="$1"

# read env from stdin
cat - | while read -r line 
do
	match1="$(echo $line | grep -e "^$var=."|| true)"
	match2="$(echo $line | grep -e "^export $var=."|| true)"
	[ -z "$match1" ] && [ -z "$match2" ] && continue

	cutlen=$(( ${#var} + 2 ))
	[ -n "$match2" ] && cutlen=$(( ${#var} + 9 ))
	echo $line | cut -c $cutlen-
done
